# Generated by Django 5.2.8 on 2025-11-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tabibi_models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="id_scan",
            field=models.FileField(blank=True, null=True, upload_to="id_scans/"),
        ),
    ]
